name: RotatorWrench
version: '1.0'
main: rotatorwrench.RotatorWrenchPlugin
api-version: '1.20'
commands:
  rotator:
    description: Rotates blocks
    usage: /rotator or /rot
    aliases:
      - rotator
      - rot
    default: true